import { BlogDetail } from "@/interface/blog";
import { GetServerSideProps } from "next";
import { AppContext } from "next/app";
import { getBlogDetail } from "server/blogs";
import parse from 'html-react-parser';
import detail from './id.module.css';
import Head from "next/head";
import BlogHeader from "@/components/BlogHeader";

export default function BlogPage({ blogData }: { blogData: BlogDetail }) {

  // console.log(blogData)
  const { author, title, bodyHTML, createdAt } = blogData;
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="layout">
      <div className="max-w-[50%]">
        <h1 className="text-center my-10 text-[2rem] font-bold"> {title} </h1>
        <div className="flex justify-center mb-4">
          <BlogHeader createdAt={createdAt} author={author} />
        </div>
        <div className={`${detail.html} flex flex-col`}>{parse(bodyHTML)}</div>
      </div>
    </section>

    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const route: string[] | string | undefined = context.query.id;

  if (!!!route) return {
    props: {
      blogData: {}
    }, // will be passed to the page component as props
  }

  const post: BlogDetail = await getBlogDetail(parseInt(route.toString(), 0));

  return {
    props: {
      blogData: post
    }, // will be passed to the page component as props
  }
}
