
import { BlogDetail } from "@/interface/blog";
import { GetServerSideProps } from "next";
import { AppContext } from "next/app";
import { getBlogDetail } from "server/blogs";
import parse from 'html-react-parser';
import Head from "next/head";
import BlogHeader from "@/components/BlogHeader";
import style from './BlogPage.module.css';
import { useEffect } from "react";

interface BlogProps {
  blogData: BlogDetail
}
export default function BlogPage({ blogData }: { blogData: BlogDetail }) {

  const { author, title, bodyHTML, createdAt } = blogData;

  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <section className="layout">
        <div className="max-w-[720px] w-full">
          <h1 className="text-center my-10 text-[2rem] font-bold"> {title} </h1>
          <div className="flex justify-center mb-4">
            <BlogHeader createdAt={createdAt} author={author} />
          </div>
          <div className={`
          markdown-body 
          ${style.cus_markdown} 
          flex flex-col 
          px-4 bg-zinc-800 mb-12
        `}>

            {parse(bodyHTML)}
          </div>
        </div>
      </section>

    </>
  );
}

